// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DomainOperationClockGetRequest {}
impl ::prost::Name for DomainOperationClockGetRequest {
    const NAME: &'static str = "DomainOperationClockGetRequest";
    const PACKAGE: &'static str = "lore.domain.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.domain.v1.DomainOperationClockGetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.domain.v1.DomainOperationClockGetRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DomainOperationClockGetResponse {
    #[prost(int64, tag = "1")]
    pub lore_clock_unix_millis: i64,
    #[prost(bytes = "bytes", tag = "2")]
    pub sample_nonce: ::prost::bytes::Bytes,
}
impl ::prost::Name for DomainOperationClockGetResponse {
    const NAME: &'static str = "DomainOperationClockGetResponse";
    const PACKAGE: &'static str = "lore.domain.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.domain.v1.DomainOperationClockGetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.domain.v1.DomainOperationClockGetResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DomainOperationPrepareRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub org_uuid: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "2")]
    pub initiating_principal_namespace: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "3")]
    pub operation_id: ::prost::bytes::Bytes,
    #[prost(string, tag = "4")]
    pub method: ::prost::alloc::string::String,
    #[prost(bytes = "bytes", tag = "5")]
    pub scope: ::prost::bytes::Bytes,
    #[prost(uint32, tag = "6")]
    pub fingerprint_version: u32,
    #[prost(bytes = "bytes", tag = "7")]
    pub fingerprint: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "8")]
    pub canonical_intent_digest: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "9")]
    pub authorization_id: ::prost::bytes::Bytes,
    #[prost(uint64, tag = "10")]
    pub authorization_revision: u64,
    /// Decoded 32-byte one-use preclaim ticket. Never logged or persisted.
    #[prost(bytes = "bytes", tag = "11")]
    pub preclaim_ticket: ::prost::bytes::Bytes,
}
impl ::prost::Name for DomainOperationPrepareRequest {
    const NAME: &'static str = "DomainOperationPrepareRequest";
    const PACKAGE: &'static str = "lore.domain.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.domain.v1.DomainOperationPrepareRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.domain.v1.DomainOperationPrepareRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DomainOperationPrepareResponse {
    #[prost(enumeration = "DomainOperationPrepareStatus", tag = "1")]
    pub status: i32,
    /// Present only for PREPARED.
    #[prost(bytes = "bytes", tag = "2")]
    pub consume_token: ::prost::bytes::Bytes,
    #[prost(int64, optional, tag = "3")]
    pub hard_expires_at_unix_millis: ::core::option::Option<i64>,
    /// Present only for COMMITTED.
    #[prost(enumeration = "DomainOperationOutcome", tag = "4")]
    pub outcome: i32,
    #[prost(uint32, optional, tag = "5")]
    pub reason_version: ::core::option::Option<u32>,
    #[prost(string, tag = "6")]
    pub reason: ::prost::alloc::string::String,
    /// Immutable platform-verification witness recorded with PREPARED/receipt.
    #[prost(bytes = "bytes", tag = "7")]
    pub verification_nonce: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "8")]
    pub bound_fields_digest: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "9")]
    pub consumed_ticket_sha256: ::prost::bytes::Bytes,
    #[prost(uint64, tag = "10")]
    pub authorization_revision: u64,
}
impl ::prost::Name for DomainOperationPrepareResponse {
    const NAME: &'static str = "DomainOperationPrepareResponse";
    const PACKAGE: &'static str = "lore.domain.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.domain.v1.DomainOperationPrepareResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.domain.v1.DomainOperationPrepareResponse".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DomainOperationReceiptGetRequest {
    #[prost(bytes = "bytes", tag = "1")]
    pub org_uuid: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "2")]
    pub initiating_principal_namespace: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "3")]
    pub operation_id: ::prost::bytes::Bytes,
    #[prost(string, tag = "4")]
    pub method: ::prost::alloc::string::String,
    #[prost(bytes = "bytes", tag = "5")]
    pub scope: ::prost::bytes::Bytes,
    #[prost(uint32, tag = "6")]
    pub fingerprint_version: u32,
    #[prost(bytes = "bytes", tag = "7")]
    pub fingerprint: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "8")]
    pub canonical_intent_digest: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "9")]
    pub authorization_id: ::prost::bytes::Bytes,
    #[prost(uint64, tag = "10")]
    pub authorization_revision: u64,
    /// Exact 32-byte commitment persisted after the prepare ticket is consumed.
    #[prost(bytes = "bytes", tag = "11")]
    pub consumed_ticket_sha256: ::prost::bytes::Bytes,
}
impl ::prost::Name for DomainOperationReceiptGetRequest {
    const NAME: &'static str = "DomainOperationReceiptGetRequest";
    const PACKAGE: &'static str = "lore.domain.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.domain.v1.DomainOperationReceiptGetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.domain.v1.DomainOperationReceiptGetRequest".into()
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DomainOperationReceiptGetResponse {
    #[prost(enumeration = "DomainOperationReceiptStatus", tag = "1")]
    pub status: i32,
    /// Present only for COMMITTED.
    #[prost(enumeration = "DomainOperationOutcome", tag = "2")]
    pub outcome: i32,
    #[prost(uint32, optional, tag = "3")]
    pub reason_version: ::core::option::Option<u32>,
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub from_future_marker: bool,
    /// Present only for PREPARED.
    #[prost(int64, optional, tag = "6")]
    pub prepared_at_unix_millis: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "7")]
    pub hard_expires_at_unix_millis: ::core::option::Option<i64>,
    /// Exact verified witness. Receipt lookup never returns the consume token.
    #[prost(bytes = "bytes", tag = "8")]
    pub verification_nonce: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "9")]
    pub bound_fields_digest: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "10")]
    pub consumed_ticket_sha256: ::prost::bytes::Bytes,
    #[prost(uint64, tag = "11")]
    pub authorization_revision: u64,
}
impl ::prost::Name for DomainOperationReceiptGetResponse {
    const NAME: &'static str = "DomainOperationReceiptGetResponse";
    const PACKAGE: &'static str = "lore.domain.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.domain.v1.DomainOperationReceiptGetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.domain.v1.DomainOperationReceiptGetResponse".into()
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DomainOperationPrepareStatus {
    Unspecified = 0,
    Prepared = 1,
    Committed = 2,
    ExpiredOrUnknown = 3,
    Mismatch = 4,
    CapacityExhausted = 5,
}
impl DomainOperationPrepareStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DOMAIN_OPERATION_PREPARE_STATUS_UNSPECIFIED",
            Self::Prepared => "DOMAIN_OPERATION_PREPARE_STATUS_PREPARED",
            Self::Committed => "DOMAIN_OPERATION_PREPARE_STATUS_COMMITTED",
            Self::ExpiredOrUnknown => {
                "DOMAIN_OPERATION_PREPARE_STATUS_EXPIRED_OR_UNKNOWN"
            }
            Self::Mismatch => "DOMAIN_OPERATION_PREPARE_STATUS_MISMATCH",
            Self::CapacityExhausted => {
                "DOMAIN_OPERATION_PREPARE_STATUS_CAPACITY_EXHAUSTED"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DOMAIN_OPERATION_PREPARE_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "DOMAIN_OPERATION_PREPARE_STATUS_PREPARED" => Some(Self::Prepared),
            "DOMAIN_OPERATION_PREPARE_STATUS_COMMITTED" => Some(Self::Committed),
            "DOMAIN_OPERATION_PREPARE_STATUS_EXPIRED_OR_UNKNOWN" => {
                Some(Self::ExpiredOrUnknown)
            }
            "DOMAIN_OPERATION_PREPARE_STATUS_MISMATCH" => Some(Self::Mismatch),
            "DOMAIN_OPERATION_PREPARE_STATUS_CAPACITY_EXHAUSTED" => {
                Some(Self::CapacityExhausted)
            }
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DomainOperationOutcome {
    Unspecified = 0,
    Applied = 1,
    NotApplied = 2,
}
impl DomainOperationOutcome {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DOMAIN_OPERATION_OUTCOME_UNSPECIFIED",
            Self::Applied => "DOMAIN_OPERATION_OUTCOME_APPLIED",
            Self::NotApplied => "DOMAIN_OPERATION_OUTCOME_NOT_APPLIED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DOMAIN_OPERATION_OUTCOME_UNSPECIFIED" => Some(Self::Unspecified),
            "DOMAIN_OPERATION_OUTCOME_APPLIED" => Some(Self::Applied),
            "DOMAIN_OPERATION_OUTCOME_NOT_APPLIED" => Some(Self::NotApplied),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DomainOperationReceiptStatus {
    Unspecified = 0,
    Prepared = 1,
    Committed = 2,
    Mismatch = 3,
    Expired = 4,
    ExpiredOrUnknown = 5,
    NotFound = 6,
}
impl DomainOperationReceiptStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DOMAIN_OPERATION_RECEIPT_STATUS_UNSPECIFIED",
            Self::Prepared => "DOMAIN_OPERATION_RECEIPT_STATUS_PREPARED",
            Self::Committed => "DOMAIN_OPERATION_RECEIPT_STATUS_COMMITTED",
            Self::Mismatch => "DOMAIN_OPERATION_RECEIPT_STATUS_MISMATCH",
            Self::Expired => "DOMAIN_OPERATION_RECEIPT_STATUS_EXPIRED",
            Self::ExpiredOrUnknown => {
                "DOMAIN_OPERATION_RECEIPT_STATUS_EXPIRED_OR_UNKNOWN"
            }
            Self::NotFound => "DOMAIN_OPERATION_RECEIPT_STATUS_NOT_FOUND",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DOMAIN_OPERATION_RECEIPT_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "DOMAIN_OPERATION_RECEIPT_STATUS_PREPARED" => Some(Self::Prepared),
            "DOMAIN_OPERATION_RECEIPT_STATUS_COMMITTED" => Some(Self::Committed),
            "DOMAIN_OPERATION_RECEIPT_STATUS_MISMATCH" => Some(Self::Mismatch),
            "DOMAIN_OPERATION_RECEIPT_STATUS_EXPIRED" => Some(Self::Expired),
            "DOMAIN_OPERATION_RECEIPT_STATUS_EXPIRED_OR_UNKNOWN" => {
                Some(Self::ExpiredOrUnknown)
            }
            "DOMAIN_OPERATION_RECEIPT_STATUS_NOT_FOUND" => Some(Self::NotFound),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod domain_operation_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// FORK-LOCAL (Tideshift, CR-029). This private server-only service is the
    /// prepare/receipt rail for Lorehub's control plane. The current API-first slice
    /// pins these on-the-wire method paths:
    /// /lore.domain.v1.DomainOperationService/DomainOperationClockGet
    /// /lore.domain.v1.DomainOperationService/DomainOperationPrepare
    /// /lore.domain.v1.DomainOperationService/DomainOperationReceiptGet
    /// No upstream package claims lore.domain.v1 today. If upstream adds that
    /// package or any method/message below, reconcile names and every field/enum tag
    /// before regeneration. CR-029's remaining four v2 methods are not declared
    /// until their store contracts exist; this partial rail must not advertise the
    /// domain_operation_receipt_v2 capability.
    #[derive(Debug, Clone)]
    pub struct DomainOperationServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl DomainOperationServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> DomainOperationServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> DomainOperationServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            DomainOperationServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn domain_operation_clock_get(
            &mut self,
            request: impl tonic::IntoRequest<super::DomainOperationClockGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DomainOperationClockGetResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.domain.v1.DomainOperationService/DomainOperationClockGet",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.domain.v1.DomainOperationService",
                        "DomainOperationClockGet",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn domain_operation_prepare(
            &mut self,
            request: impl tonic::IntoRequest<super::DomainOperationPrepareRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DomainOperationPrepareResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.domain.v1.DomainOperationService/DomainOperationPrepare",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.domain.v1.DomainOperationService",
                        "DomainOperationPrepare",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn domain_operation_receipt_get(
            &mut self,
            request: impl tonic::IntoRequest<super::DomainOperationReceiptGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DomainOperationReceiptGetResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.domain.v1.DomainOperationService/DomainOperationReceiptGet",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.domain.v1.DomainOperationService",
                        "DomainOperationReceiptGet",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod domain_operation_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with DomainOperationServiceServer.
    #[async_trait]
    pub trait DomainOperationService: std::marker::Send + std::marker::Sync + 'static {
        async fn domain_operation_clock_get(
            &self,
            request: tonic::Request<super::DomainOperationClockGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DomainOperationClockGetResponse>,
            tonic::Status,
        >;
        async fn domain_operation_prepare(
            &self,
            request: tonic::Request<super::DomainOperationPrepareRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DomainOperationPrepareResponse>,
            tonic::Status,
        >;
        async fn domain_operation_receipt_get(
            &self,
            request: tonic::Request<super::DomainOperationReceiptGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DomainOperationReceiptGetResponse>,
            tonic::Status,
        >;
    }
    /// FORK-LOCAL (Tideshift, CR-029). This private server-only service is the
    /// prepare/receipt rail for Lorehub's control plane. The current API-first slice
    /// pins these on-the-wire method paths:
    /// /lore.domain.v1.DomainOperationService/DomainOperationClockGet
    /// /lore.domain.v1.DomainOperationService/DomainOperationPrepare
    /// /lore.domain.v1.DomainOperationService/DomainOperationReceiptGet
    /// No upstream package claims lore.domain.v1 today. If upstream adds that
    /// package or any method/message below, reconcile names and every field/enum tag
    /// before regeneration. CR-029's remaining four v2 methods are not declared
    /// until their store contracts exist; this partial rail must not advertise the
    /// domain_operation_receipt_v2 capability.
    #[derive(Debug)]
    pub struct DomainOperationServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> DomainOperationServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for DomainOperationServiceServer<T>
    where
        T: DomainOperationService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/lore.domain.v1.DomainOperationService/DomainOperationClockGet" => {
                    #[allow(non_camel_case_types)]
                    struct DomainOperationClockGetSvc<T: DomainOperationService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: DomainOperationService,
                    > tonic::server::UnaryService<super::DomainOperationClockGetRequest>
                    for DomainOperationClockGetSvc<T> {
                        type Response = super::DomainOperationClockGetResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::DomainOperationClockGetRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DomainOperationService>::domain_operation_clock_get(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DomainOperationClockGetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.domain.v1.DomainOperationService/DomainOperationPrepare" => {
                    #[allow(non_camel_case_types)]
                    struct DomainOperationPrepareSvc<T: DomainOperationService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: DomainOperationService,
                    > tonic::server::UnaryService<super::DomainOperationPrepareRequest>
                    for DomainOperationPrepareSvc<T> {
                        type Response = super::DomainOperationPrepareResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DomainOperationPrepareRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DomainOperationService>::domain_operation_prepare(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DomainOperationPrepareSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.domain.v1.DomainOperationService/DomainOperationReceiptGet" => {
                    #[allow(non_camel_case_types)]
                    struct DomainOperationReceiptGetSvc<T: DomainOperationService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: DomainOperationService,
                    > tonic::server::UnaryService<
                        super::DomainOperationReceiptGetRequest,
                    > for DomainOperationReceiptGetSvc<T> {
                        type Response = super::DomainOperationReceiptGetResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::DomainOperationReceiptGetRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DomainOperationService>::domain_operation_receipt_get(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DomainOperationReceiptGetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for DomainOperationServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "lore.domain.v1.DomainOperationService";
    impl<T> tonic::server::NamedService for DomainOperationServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
