// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateResourceRequest {
    #[prost(string, tag = "1")]
    pub resource_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub resource_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateResourceResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteResourceRequest {
    #[prost(string, tag = "1")]
    pub resource_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteResourceResponse {}
/// Exact private CR-029 authorization identity and caller-known operation
/// binding. The issuer and subject are supplied by loreserver from the verified
/// JWT extension. They are never copied from the public DomainOperation request.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyRepositoryOperationAuthorizationRequest {
    #[prost(string, tag = "1")]
    pub verified_issuer: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub authenticated_subject: ::prost::alloc::string::String,
    #[prost(bytes = "bytes", tag = "3")]
    pub org_uuid: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "4")]
    pub initiating_principal_namespace: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "5")]
    pub operation_id: ::prost::bytes::Bytes,
    #[prost(string, tag = "6")]
    pub method: ::prost::alloc::string::String,
    #[prost(bytes = "bytes", tag = "7")]
    pub scope: ::prost::bytes::Bytes,
    #[prost(uint32, tag = "8")]
    pub fingerprint_version: u32,
    #[prost(bytes = "bytes", tag = "9")]
    pub fingerprint: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "10")]
    pub canonical_intent_digest: ::prost::bytes::Bytes,
    /// CR-029 freezes authorization_id to the canonical operation UUID until a
    /// separate authorization-id column exists. The verifier requires equality.
    #[prost(bytes = "bytes", tag = "11")]
    pub authorization_id: ::prost::bytes::Bytes,
    #[prost(uint64, tag = "12")]
    pub authorization_revision: u64,
    #[prost(
        oneof = "verify_repository_operation_authorization_request::Proof",
        tags = "13, 14"
    )]
    pub proof: ::core::option::Option<
        verify_repository_operation_authorization_request::Proof,
    >,
}
/// Nested message and enum types in `VerifyRepositoryOperationAuthorizationRequest`.
pub mod verify_repository_operation_authorization_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Proof {
        /// Decoded 32-byte one-use secret. Consumes ISSUED -> VERIFIED.
        #[prost(bytes, tag = "13")]
        PreclaimTicket(::prost::bytes::Bytes),
        /// Exact 32-byte commitment. Read-only verification for receipt lookup.
        #[prost(bytes, tag = "14")]
        ConsumedTicketSha256(::prost::bytes::Bytes),
    }
}
/// The immutable witness persisted beside PREPARED, plus an exact echo of every
/// identity/binding field. Loreserver rejects any divergent echo before it
/// creates or reads a receipt.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyRepositoryOperationAuthorizationResponse {
    #[prost(bytes = "bytes", tag = "1")]
    pub authorization_id: ::prost::bytes::Bytes,
    #[prost(uint64, tag = "2")]
    pub authorization_revision: u64,
    #[prost(bytes = "bytes", tag = "3")]
    pub verification_nonce: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "4")]
    pub bound_fields_digest: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "5")]
    pub consumed_ticket_sha256: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "6")]
    pub org_uuid: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "7")]
    pub initiating_principal_namespace: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "8")]
    pub operation_id: ::prost::bytes::Bytes,
    #[prost(string, tag = "9")]
    pub method: ::prost::alloc::string::String,
    #[prost(bytes = "bytes", tag = "10")]
    pub scope: ::prost::bytes::Bytes,
    #[prost(uint32, tag = "11")]
    pub fingerprint_version: u32,
    #[prost(bytes = "bytes", tag = "12")]
    pub fingerprint: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "13")]
    pub canonical_intent_digest: ::prost::bytes::Bytes,
    #[prost(string, tag = "14")]
    pub verified_issuer: ::prost::alloc::string::String,
    #[prost(string, tag = "15")]
    pub authenticated_subject: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod rebac_api_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct RebacApiClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RebacApiClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RebacApiClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RebacApiClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            RebacApiClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn create_resource(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateResourceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateResourceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ucs.auth.RebacApi/CreateResource",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ucs.auth.RebacApi", "CreateResource"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_resource(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteResourceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteResourceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ucs.auth.RebacApi/DeleteResource",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ucs.auth.RebacApi", "DeleteResource"));
            self.inner.unary(req, path, codec).await
        }
        /// FORK-LOCAL (Tideshift, CR-029). Private server-to-auth callback. Additive:
        /// one RPC and new messages, with no existing field number or method changed.
        /// The on-the-wire method path is
        /// /ucs.auth.RebacApi/VerifyRepositoryOperationAuthorization. Lore's private
        /// domain prepare/receipt rail is pinned to that exact path. If upstream adds
        /// an authorization-verification RPC or messages with these names, reconcile
        /// the method path and every field tag before regenerating this binding.
        pub async fn verify_repository_operation_authorization(
            &mut self,
            request: impl tonic::IntoRequest<
                super::VerifyRepositoryOperationAuthorizationRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<super::VerifyRepositoryOperationAuthorizationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ucs.auth.RebacApi/VerifyRepositoryOperationAuthorization",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ucs.auth.RebacApi",
                        "VerifyRepositoryOperationAuthorization",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
