# SPDX-FileCopyrightText: 2026 Tideshift Labs
# SPDX-License-Identifier: MIT
[package]
name = "lore-object-dispatch"
edition = "2024"
version.workspace = true
publish = false

[dependencies]
base64 = { workspace = true }
blake3 = { workspace = true }
lore-base = { workspace = true }
lore-proto = { workspace = true }
lore-telemetry = { workspace = true }
opentelemetry = { workspace = true }
prost = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = "2"
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { version = "0.7", features = ["with-uuid-1"] }
tokio-postgres-rustls = { version = "0.13", default-features = false }
tokio-stream = { workspace = true, features = ["net"] }
tokio-util = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
unicode-normalization = "0.1.25"
uuid = { workspace = true }
x509-parser = { workspace = true }

[dev-dependencies]
rcgen = { workspace = true }
