// SPDX-FileCopyrightText: 2026 Epic Games, Inc.
// Copyright 2026 Khurram Virani
// SPDX-License-Identifier: MIT
//! FFI error code trait.
//!
//! [`FfiError`] provides a standard way for error types to expose an integer
//! error code suitable for FFI boundaries. Discrete error types implement this
//! trait directly, and error sets auto-inherit FFI codes via generated
//! delegation.

/// Trait for errors that carry an FFI-compatible integer error code.
///
/// Discrete error types implement this trait to define their FFI code once.
/// Error sets generated by `#[error_set]` automatically delegate to each
/// variant's `ffi_code()`.
///
/// # Example
///
/// ```
/// use lore_error_set::FfiError;
///
/// #[derive(Debug)]
/// struct NotFound;
///
/// impl std::fmt::Display for NotFound {
///     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
///         write!(f, "not found")
///     }
/// }
///
/// impl std::error::Error for NotFound {}
///
/// impl FfiError for NotFound {
///     fn ffi_code(&self) -> i32 { 1 }
/// }
///
/// let err = NotFound;
/// assert_eq!(err.ffi_code(), 1);
/// ```
pub trait FfiError {
    /// Returns the FFI error code for this error.
    fn ffi_code(&self) -> i32;

    /// The operation and attempt this error names, for the errors that name one.
    ///
    /// `None` for almost everything, and that is the point: an error code tells a consumer what
    /// went wrong, but an outcome-unknown error additionally has to say *which attempt* it went
    /// wrong for, because the consumer's next move is to look that attempt up. A code alone
    /// cannot carry that, and a caller that had to parse it out of the `Display` string would be
    /// depending on prose as a contract.
    ///
    /// Returned as borrowed strings so an FFI boundary can copy them without this trait
    /// committing to an allocation for the overwhelmingly common `None` case. Sets generated by
    /// `#[error_set]` delegate to their variants exactly as they do for
    /// [`FfiError::ffi_code`], so a set carrying a variant that names an attempt reports it
    /// without any per-set code.
    fn outcome_identity(&self) -> Option<(&str, &str)> {
        None
    }
}
